"""initial

Revision ID: f24da11bbd70
Revises: 
Create Date: 2026-06-16 09:59:22.963579
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'f24da11bbd70'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'OPERATOR', 'VIEWER', 'API', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_key'), 'api_keys', ['key'], unique=True)
    op.create_table('cameras',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=512), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('detect_enabled', sa.Boolean(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('fps', sa.Integer(), nullable=True),
    sa.Column('conf_thresh', sa.Float(), nullable=True),
    sa.Column('zones', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'OPERATOR', 'VIEWER', 'API', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('camera_id', sa.String(length=64), nullable=False),
    sa.Column('label', sa.Enum('VIOLATION', 'APPROVED', 'DANGER_ZONE', 'MOTION', 'HEARTBEAT', name='eventlabel'), nullable=False),
    sa.Column('sub_label', sa.Enum('NO_HELMET', 'NO_MASK', 'NO_VEST', 'NO_GLASSES', 'DANGER_ZONE', 'OK_GESTURE', 'RAISED_HAND', 'PERSON_ENTER', 'PERSON_EXIT', 'GENERAL', name='sublabel'), nullable=True),
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=True),
    sa.Column('has_clip', sa.Boolean(), nullable=True),
    sa.Column('has_snapshot', sa.Boolean(), nullable=True),
    sa.Column('zones', sa.JSON(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('person_name', sa.String(length=128), nullable=True),
    sa.Column('ppe_helmet', sa.Boolean(), nullable=True),
    sa.Column('ppe_mask', sa.Boolean(), nullable=True),
    sa.Column('ppe_vest', sa.Boolean(), nullable=True),
    sa.Column('ppe_glasses', sa.Boolean(), nullable=True),
    sa.Column('box_x', sa.Integer(), nullable=True),
    sa.Column('box_y', sa.Integer(), nullable=True),
    sa.Column('box_w', sa.Integer(), nullable=True),
    sa.Column('box_h', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_camera_id'), 'events', ['camera_id'], unique=False)
    op.create_index('ix_events_camera_time', 'events', ['camera_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_events_label'), 'events', ['label'], unique=False)
    op.create_index('ix_events_label_time', 'events', ['label', 'timestamp'], unique=False)
    op.create_index(op.f('ix_events_person_id'), 'events', ['person_id'], unique=False)
    op.create_index(op.f('ix_events_sub_label'), 'events', ['sub_label'], unique=False)
    op.create_index(op.f('ix_events_timestamp'), 'events', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_timestamp'), table_name='events')
    op.drop_index(op.f('ix_events_sub_label'), table_name='events')
    op.drop_index(op.f('ix_events_person_id'), table_name='events')
    op.drop_index('ix_events_label_time', table_name='events')
    op.drop_index(op.f('ix_events_label'), table_name='events')
    op.drop_index('ix_events_camera_time', table_name='events')
    op.drop_index(op.f('ix_events_camera_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('cameras')
    op.drop_index(op.f('ix_api_keys_key'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
